title: Play a sound on collision
hero_image: images/banner.png
description: Play a sound on collision in Unity
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Play a sound on collision
